### PR TITLE
Fix duplicate submit button not triggering `getPressedSubmitElement()`

### LINKED ISSUE #132: Submitting a form by pushing Enter does not work
That's because only the attributes are cloned and the label that has been set on the original submit button is a property of the element.

### PR DESCRIPTION
**Pull request by TAINCER**
The duplicated submit button does not have the same label as the original submit element. Thus the check in [getPressedSubmitElement()](https://github.com/Icinga/ipl-html/blob/8740b9efd42607e1b03a792897a9d3d51bc01e7f/src/Form.php#L148) can never be `true`.

The submit button check [hasBeenPressed()](https://github.com/Icinga/ipl-html/blob/8740b9efd42607e1b03a792897a9d3d51bc01e7f/src/FormElement/SubmitElement.php#L43) expects the label in the if statement, currently the name is given.

fixes #132

### CODE REVIEW

File: src/Compat/CompatForm.php [hunk 1]
```diff
@@ -61,6 +61,14 @@ public function duplicateSubmitButton(FormSubmitElement $originalSubmitButton):
             ->set('class', 'primary-submit-btn-duplicate');
         $attributes->remove('id');
 
-        return new SubmitElement($originalSubmitButton->getName(), $attributes);
+        $newSubmitButton = new SubmitElement($originalSubmitButton->getName(), $attributes);
+
+        if ($originalSubmitButton instanceof SubmitElement) {
+            $newSubmitButton->setLabel($originalSubmitButton->getButtonLabel());
+        } else {
+            $newSubmitButton->setLabel($originalSubmitButton->getLabel());
```
Comment (nilmerg) [inline src/Compat/CompatForm.php:69]: The label of SubmitButtonElements have no purpose in this regard, they exist only for display reasons. It's the submit value that needs to be kept in this case.

**Review by nilmerg — CHANGES_REQUESTED** [review]
Also, please fix/extend the tests. They're also flawed.

File: src/Compat/CompatForm.php [hunk 2]
```diff
@@ -53,14 +55,30 @@ public function hasDefaultElementDecorator()
      *
      * @param FormSubmitElement $originalSubmitButton
      *
-     * @return SubmitElement
+     * @return SubmitButtonElement
```
Comment (nilmerg) [inline src/Compat/CompatForm.php:58]: This should be `FormSubmitElement`

File: src/Compat/CompatForm.php [hunk 3]
```diff
@@ -53,14 +55,30 @@ public function hasDefaultElementDecorator()
...
+        $attributes->remove('type');
 
-        return new SubmitElement($originalSubmitButton->getName(), $attributes);
+        if ($originalSubmitButton instanceof SubmitElement) {
+            $newSubmitButton = new SubmitElement($originalSubmitButton->getName(), $attributes);
+            $newSubmitButton->setLabel($originalSubmitButton->getButtonLabel());
+            return $newSubmitButton;
+        } elseif ($originalSubmitButton instanceof SubmitButtonElement) {
+            $newSubmitButton = new SubmitButtonElement($originalSubmitButton->getName(), $attributes);
+            $newSubmitButton->setLabel($originalSubmitButton->getSubmitValue());
```
Comment (nilmerg) [inline src/Compat/CompatForm.php:74]: That should be of no interest, it's hidden after all

File: src/Compat/CompatForm.php [hunk 4]
```diff
@@ -53,14 +55,30 @@ public function hasDefaultElementDecorator()
...
             ->set('class', 'primary-submit-btn-duplicate');
         $attributes->remove('id');
+        // Remove to avoid `type="submit submit"` in SubmitButtonElement
+        $attributes->remove('type');
 
-        return new SubmitElement($originalSubmitButton->getName(), $attributes);
+        if ($originalSubmitButton instanceof SubmitElement) {
+            $newSubmitButton = new SubmitElement($originalSubmitButton->getName(), $attributes);
+            $newSubmitButton->setLabel($originalSubmitButton->getButtonLabel());
+            return $newSubmitButton;
```
Comment (nilmerg) [inline src/Compat/CompatForm.php:71]: empty line before `return` please

**Review by nilmerg — CHANGES_REQUESTED** [review]

**Review by nilmerg — APPROVED** [review]
